### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Hanjiewu** [esteinig/sccion#3]
the following message showed when install as instructed 

> Collecting package metadata: done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - sccion
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/linux-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/bioconda/linux-64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://conda.anaconda.org/esteinig/linux-64
>   - https://conda.anaconda.org/esteinig/noarch
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/free/linux-64
>   - https://repo.anaconda.com/pkgs/free/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
>

**Comment by esteinig** [comment]
Hey, my apologies, it's not actually live yet! We are still fixing some issues, I highly recommend other programs like SCCmecFinder and Mykrobe in the meantime, but feel free to come back in a couple of weeks if you are still keen try out SCCion :)

**Comment by esteinig** [comment]
Closing issue, added better information to README

**Comment by esteinig** [comment]
`v0.1.a4` now available on `conda`:

`conda install -c bioconda -c esteinig sccion`
